blank_issues_enabled: false
contact_links:
  - name: ğŸ¤ ãƒ‡ã‚£ã‚¹ã‚«ãƒƒã‚·ãƒ§ãƒ³
    url: https://github.com/TakuyaFukumura/household-management/discussions
    about: è³ªå•ã‚„ã‚¢ã‚¤ãƒ‡ã‚¢ã«ã¤ã„ã¦è©±ã—åˆã„ãŸã„å ´åˆã¯ã“ã¡ã‚‰ã‚’ã”åˆ©ç”¨ãã ã•ã„